// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfysoixizwxkucwfeyqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeXNvaXhpend4a3Vjd2ZleXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTI0NTMsImV4cCI6MjA1MTU2ODQ1M30.FPV3GKTvT8KCK5w9fmFzLjgQwmWhS9wzaERSTeclpqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);