// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhsadbbvdjucgqisrcen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoc2FkYmJ2ZGp1Y2dxaXNyY2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMTUxMTEsImV4cCI6MjA1MTU5MTExMX0.XpPGfB2xoKX1qoZOe4hxpSSdkWeBafX-SH5Q-Kkw03E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);